 name: Arsal kamran

 on:
    push:
       branch: [ main ]

 jobs:
    demo:
       runs-on: ubuntu-latest

       steps:
         - name: greetings
           run:  echo "helo from arsal"
         

